### ISSUE TITLE
Decide if 361.28 is ready for Manjaro

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-extra#49] opened 2016-02-09 22:25 UTC
Release highlights since 361.18:

* Added support for the following GPUs:
  - GeForce 945A
  - Tesla M4

* Added a legacy, non-GLVND libGL.so GLX client library to the NVIDIA Linux driver installer package, and the ability to select between a GLVND or non-GLVND GLX client library at installation time. This allows users to install the legacy non-GLVND GLX client library in order to work around compatibility issues which may arise due to GLX applications which depend upon behaviors of the NVIDIA GLX client driver which are not defined by the Linux OpenGL ABI version 1.0.

* By default, nvidia-installer will install the legacy, non-GLVND GLX client libraries. The --glvnd-glx-client command line option can be used to override the default, and install the GLVND GLX client libraries instead. Please contact the vendors of any applications that are not compatible with GLVND to ensure that their applications be updated for compatibility with GLVND.

* The presence of multiple GLX client libraries in the package has implications for repackagers of the NVIDIA driver; see the libGL.so entry in the "Installed Components" chapter of the README and the thread Multiple GLX client libraries in the NVIDIA Linux driver installer package for details.

**Comment by philmmanjaro** [comment] 2016-02-09 22:29
Found issues at devtalk:

[[361.28] duplicate lines in .manifest file ](https://devtalk.nvidia.com/default/topic/915808/linux/-361-28-duplicate-lines-in-manifest-file-/)
[361.xx [361.18, 361.28] segfault - nvidia 840m - optimus](https://devtalk.nvidia.com/default/topic/915761/linux/361-xx-361-18-361-28-segfault-nvidia-840m-optimus/)
[XCOM 2 performance regression with 361.18](https://devtalk.nvidia.com/default/topic/915579/linux/xcom-2-performance-regression-with-361-18/)

**Comment by philmmanjaro** [comment] 2016-02-09 22:34
Notable changes:

* [libGL.so.1.0.0 linkage](https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/nvidia-utils&id=36c06bed1bd3efab5acdbac1ab2b57c7230ca391)
* [opt. lib libnvidia-wfb.so removal](https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/nvidia-utils&id=e5bcaebb48f2ba5831ac36b61e5461a283376470)
* [libGLX and other libs introduction](https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/nvidia-utils&id=c4159bf1cf0ca58fec0200103e4af581d6648855)
* [sev. lib addtions](https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/nvidia-utils&id=4469dc1e76d8a5e3098572fc8a8867b12101c7a5)

**Comment by philmmanjaro** [comment] 2016-02-09 22:34
Decide if changes to **mhwd** is needed.

**Comment by FadeMind** [comment] 2016-02-10 07:07
@philmmanjaro 
One typo: 361.**2**8
![screenshot_20160210_080645](https://cloud.githubusercontent.com/assets/9846948/12940839/3d6c53ce-cfcd-11e5-8af0-e484dccc5ba3.png)

**Comment by FadeMind** [comment] 2016-02-10 19:34
@philmmanjaro : fun begin... https://bugs.archlinux.org/task/48123

**Comment by philmmanjaro** [comment] 2016-02-11 06:29
@FadeMind: The problem is not in **nvidia-utils** rather in **libglvnd** and **bumblebee** not supporting it yet.

**Comment by Borderliner** [comment] 2016-02-15 20:31
Also note that 361.28 fixed a bug in "Konsole" KDE App where it uses CPU in the background.
[https://bugs.kde.org/show_bug.cgi?id=343803](Bug 343803)

**Comment by udeved** [comment] 2016-03-25 19:04
364.12 supposedly fixes the dvi resolution problem.
Will report once I have it tested on gentoo.

**Comment by udeved** [comment] 2016-03-25 19:15
I can confirm 364.12 to fix the dvi issue as reported on nvidia devtalk.

**Comment by FadeMind** [comment] 2016-03-25 19:23
@udeved @philmmanjaro 
364.12 provide new file module `nvidia-drm` . 
DKMS build on 4.5 kernel version went fine.
Working FINE. 
NOTE: mhwd-gpu should blacklist `nvidia-drm` module too (bumblebee variants).
Reference: https://github.com/manjaro/mhwd-db/commit/44946b35275bc5c78831709a4a585001f873d980

**Comment by udeved** [comment] 2016-03-25 19:27
@FadeMind 

I have 364.12 running with kernel 4.1.15-r1

**Comment by Kirek** [comment] 2016-03-30 18:08
https://devtalk.nvidia.com/default/topic/928139/unix-graphics-announcements-and-news/linux-solaris-and-freebsd-driver-361-42-long-lived-branch-release-/

**Comment by jetm** [comment] 2016-03-30 20:28
As @Kirek shared the [link](https://devtalk.nvidia.com/default/topic/928139/unix-graphics-announcements-and-news/linux-solaris-and-freebsd-driver-361-42-long-lived-branch-release-/) now nvidia 361.xx is a long-lived branch release. I see it as a good reason to add it and upgrade mhwd-nvidia package. I guess 352.xx long-lived series will be supported; it might be useful to create mhwd-nvidia-352xx package as well.

**Comment by udeved** [comment] 2016-04-02 08:57
361.42 is fine, it has the fix backported finally.

**Comment by philmmanjaro** [comment] 2016-04-02 09:57
@udeved: so your screen issue is gone with this driver release and I can update the **nvidia** package?

**Comment by udeved** [comment] 2016-04-02 11:05
Right @philmmanjaro 

    Fixed a regression that caused the HSync and VSync mode timing polarity flags to be inverted.

I think this was the one.

**Comment by udeved** [comment] 2016-04-02 17:49
@philmmanjaro 

Should we have a vidia-dkms package too? Like arch nvidia?
The dkms hooks are present with dkms package already.

**Comment by philmmanjaro** [comment] 2016-04-03 02:54
I [updated](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160328/006596.html) **nvidia** to **361.42**, please report back. Regarding **dkms**, I had to downgrade that package once again since **spl/zfs** doesn't compile with the latest git-release. However we might think about backporting the **hooks** support to our **dkms** package ...

**Comment by udeved** [comment] 2016-04-03 07:47
361.42 runs fine on manjaro too, just updated, 

Arch have a split build for now, one binary module, and one dkms approach.
Have you tried to compile with latest dkms from arch testing repo?

**Comment by philmmanjaro** [comment] 2016-04-04 15:18
No, I didn't tried **dkms** for it. We have to think about **dkms** in general. For a live-cd bootup it might take longer if we use dkms ...

**Comment by udeved** [comment] 2016-04-04 16:01
Regarding dkms, I thought the module would be built in chroot at iso buildtime, ie we would have to change mhwd layer? Triggered by post transaction dkms hook?
Wouldn't mhwd neeed changes too? In fact, there won't be a binary module package.
If I look at arch dkms package, it looks like dkms will be triggered pacman transaction.

**Comment by udeved** [comment] 2016-04-04 16:03
arch dkms....

~~~
[Trigger]
Operation = Install
Operation = Upgrade
Type = File
Target = usr/src/*/dkms.conf
Target = usr/lib/modules/*/
Target = !usr/lib/modules/extramodules-*
Target = !usr/lib/modules/*/?*

[Action]
Description = Install DKMS modules
Depends = dkms
When = PostTransaction
Exec = /usr/lib/dkms/alpm-hook install
NeedsTargets
~~~

~~~
[Trigger]
Operation = Upgrade
Operation = Remove
Type = File
Target = usr/src/*/dkms.conf
Target = usr/lib/modules/*/
Target = !usr/lib/modules/extramodules-*
Target = !usr/lib/modules/*/?*

[Action]
Description = Remove DKMS modules
Depends = dkms
When = PreTransaction
Exec = /usr/lib/dkms/alpm-hook remove -q
NeedsTargets
~~~

**Comment by udeved** [comment] 2016-04-04 16:15
Here is a snippet of the split arch nvidia PKGBUILD....

~~~
package_nvidia-dkms() {
    pkgdesc="NVIDIA driver sources for linux"
    depends=('dkms' "nvidia-utils=$pkgver" 'libgl')
    optdepends=('linux-headers: Build the module for Arch kernel'
                'linux-lts-headers: Build the module for LTS Arch kernel')
    conflicts+=('nvidia')

    cd ${_pkg}
    install -dm 755 "${pkgdir}"/usr/{lib/modprobe.d,src}
    cp -dr --no-preserve='ownership' kernel-dkms "${pkgdir}/usr/src/nvidia-${pkgver}"
    echo 'blacklist nouveau' > "${pkgdir}/usr/lib/modprobe.d/nvidia.conf"
}
~~~

**Comment by Kirek** [comment] 2016-04-11 22:02
361.42 is in the repos and seems to work fine... closing

**Closed by Kirek** 2016-04-11 22:02 UTC
Labels: question
