### ISSUE TITLE
[nvidia] latest update 355.11

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-extra#22] opened 2015-09-02 15:21 UTC
Latest update in unstable of either linux41-nvida, nvidia-utils, mhwd-nvidia is borked.
The new driver doesn't get me native resolution for my screen.
Reverting back to previous version solves it and resolution is fine.

**Comment by philmmanjaro** [comment] 2015-09-02 18:29
I tested it on my end. All seems fine here. What is your native resolution btw?

**Comment by udeved** [comment] 2015-09-02 18:37
1920x1080

Geforece gtx 460

**Comment by udeved** [comment] 2015-09-02 18:42
Btw, the driver shows native resolution, but plasma has cut off edges, clock and menu missing at least.
Already displaymanager looks wrong from proportions.

**Comment by philmmanjaro** [comment] 2015-09-02 18:44
What is the resolution you get now?  maybe [this](http://askubuntu.com/questions/100900/how-do-i-set-the-correct-monitor-resolution-with-nvidia-drivers-for-a-monitor-th) helps ...

**Comment by udeved** [comment] 2015-09-02 18:46
My screen send EDID. Benq

**Comment by udeved** [comment] 2015-09-02 18:48
I explain, nvidia settings show the driver uses 1920x1080, but the actual resolutions does not match.
At least 5 cm cut off left and right for example.

**Comment by philmmanjaro** [comment] 2015-09-02 18:52
Really weird issue. **355** series is the first nvidia driver with experimental wayland support. Also the way how they build the modules had changed. Is this issue on all kernels or only on some particular. After I finished **15.09-rc1** builds I'll update other nvidia drivers also.

**Comment by udeved** [comment] 2015-09-02 18:53
I have only tested linux41 so far.
I rolled back on 41 to 352

**Comment by philmmanjaro** [comment] 2015-09-02 18:58
If you have time, please check also other kernel combinations ...

**Comment by udeved** [comment] 2015-09-02 19:01
What kernels do you want tested? All?

**Comment by philmmanjaro** [comment] 2015-09-02 19:14
Just a few ...

**Comment by udeved** [comment] 2015-09-02 20:29
Same result for kernel40. Resolution is wrong.

**Comment by philmmanjaro** [comment] 2015-09-02 20:33
Create a screenshot from **355** and **342** and [report](https://surveys.nvidia.com/index.jsp?pi=ad1c492c9d7488731f70e8d4356ba631) it [upstream](https://devtalk.nvidia.com/default/board/98/linux/). Seems you found a regression. On my end it is fine.

**Comment by udeved** [comment] 2015-09-02 20:49
~~~
[   146.064] 
X.Org X Server 1.17.2
Release Date: 2015-06-16
[   146.064] X Protocol Version 11, Revision 0
[   146.064] Build Operating System: Linux 4.0.4-2-ARCH x86_64 
[   146.064] Current Operating System: Linux manjaro-openrc 4.0.9-1-MANJARO #1 SMP PREEMPT Wed Jul 22 07:47:40 UTC 2015 x86_64
[   146.064] Kernel command line: BOOT_IMAGE=/vmlinuz-4.0-x86_64 root=UUID=361d5ee4-fd2f-4f24-8b2a-67563a61ffed rw quiet resume=UUID=ca50dbc1-89cc-452b-90b7-566f5838fc59
[   146.064] Build Date: 17 July 2015  05:38:19PM
[   146.064]  
[   146.064] Current version of pixman: 0.32.6
[   146.064] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[   146.064] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   146.065] (==) Log file: "/var/log/Xorg.0.log", Time: Wed Sep  2 22:27:06 2015
[   146.065] (==) Using config directory: "/etc/X11/xorg.conf.d"
[   146.065] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   146.065] (==) ServerLayout "Layout0"
[   146.065] (**) |-->Screen "Screen0" (0)
[   146.065] (**) |   |-->Monitor "Monitor0"
[   146.065] (**) |   |-->Device "Device0"
[   146.065] (**) |-->Input Device "Keyboard0"
[   146.065] (**) |-->Input Device "Mouse0"
[   146.065] (==) Automatically adding devices
[   146.065] (==) Automatically enabling devices
[   146.065] (==) Automatically adding GPU devices
[   146.065] (WW) The directory "/usr/share/fonts/Type1/" does not exist.
[   146.065] 	Entry deleted from font path.
[   146.065] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/100dpi/".
[   146.065] 	Entry deleted from font path.
[   146.065] 	(Run 'mkfontdir' on "/usr/share/fonts/100dpi/").
[   146.065] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/75dpi/".
[   146.065] 	Entry deleted from font path.
[   146.065] 	(Run 'mkfontdir' on "/usr/share/fonts/75dpi/").
[   146.065] (==) FontPath set to:
	/usr/share/fonts/misc/,
	/usr/share/fonts/TTF/,
	/usr/share/fonts/OTF/
[   146.065] (==) ModulePath set to "/usr/lib/xorg/modules"
[   146.065] (**) Extension "Composite" is enabled
[   146.065] (WW) Hotplugging is on, devices using drivers 'kbd', 'mouse' or 'vmmouse' will be disabled.
[   146.065] (WW) Disabling Keyboard0
[   146.065] (WW) Disabling Mouse0
[   146.065] (II) Loader magic: 0x817d60
[   146.065] (II) Module ABI versions:
[   146.065] 	X.Org ANSI C Emulation: 0.4
[   146.065] 	X.Org Video Driver: 19.0
[   146.065] 	X.Org XInput driver : 21.1
[   146.065] 	X.Org Server Extension : 9.0
[   146.067] (EE) systemd-logind: failed to get session: The name org.freedesktop.login1 was not provided by any .service files
[   146.067] (II) xfree86: Adding drm device (/dev/dri/card0)
[   146.068] (--) PCI:*(0:1:0:0) 10de:0e22:3842:1370 rev 161, Mem @ 0xf8000000/33554432, 0xe8000000/134217728, 0xf0000000/67108864, I/O @ 0x0000e000/128, BIOS @ 0x????????/524288
[   146.068] (II) Open ACPI successful (/var/run/acpid.socket)
[   146.068] (II) LoadModule: "glx"
[   146.069] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[   146.079] (II) Module glx: vendor="NVIDIA Corporation"
[   146.079] 	compiled for 4.0.2, module version = 1.0.0
[   146.079] 	Module class: X.Org Server Extension
[   146.079] (II) NVIDIA GLX Module  352.41  Fri Aug 21 22:40:16 PDT 2015
[   146.079] (II) LoadModule: "nvidia"
[   146.079] (II) Loading /usr/lib/xorg/modules/drivers/nvidia_drv.so
[   146.080] (II) Module nvidia: vendor="NVIDIA Corporation"
[   146.080] 	compiled for 4.0.2, module version = 1.0.0
[   146.080] 	Module class: X.Org Video Driver
[   146.080] (II) NVIDIA dlloader X Driver  352.41  Fri Aug 21 22:14:01 PDT 2015
[   146.080] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
[   146.080] (++) using VT number 7

[   146.080] (II) Loading sub module "fb"
[   146.080] (II) LoadModule: "fb"
[   146.080] (II) Loading /usr/lib/xorg/modules/libfb.so
[   146.080] (II) Module fb: vendor="X.Org Foundation"
[   146.080] 	compiled for 1.17.2, module version = 1.0.0
[   146.080] 	ABI class: X.Org ANSI C Emulation, version 0.4
[   146.080] (II) Loading sub module "wfb"
[   146.080] (II) LoadModule: "wfb"
[   146.080] (II) Loading /usr/lib/xorg/modules/libwfb.so
[   146.081] (II) Module wfb: vendor="X.Org Foundation"
[   146.081] 	compiled for 1.17.2, module version = 1.0.0
[   146.081] 	ABI class: X.Org ANSI C Emulation, version 0.4
[   146.081] (II) Loading sub module "ramdac"
[   146.081] (II) LoadModule: "ramdac"
[   146.081] (II) Module "ramdac" already built-in
[   146.081] (EE) NVIDIA: Failed to initialize the NVIDIA kernel module. Please see the
[   146.081] (EE) NVIDIA:     system's kernel log for additional error messages and
[   146.081] (EE) NVIDIA:     consult the NVIDIA README for details.
[   146.081] (EE) No devices detected.
[   146.081] (EE) 
Fatal server error:
[   146.081] (EE) no screens found(EE) 
[   146.081] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[   146.081] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[   146.081] (EE) 
~~~

~~~
 manjaro-openrc kernel: NVRM: API mismatch: the client has the version 352.41, but\x0aNVRM: this kernel module has the version 355.11.  Please\x0aNVRM: make sure that this kernel module and all NVIDIA driver\x0aNVRM: components have the same version.
Sep  2 22:27:06 manjaro-openrc kernel: NVRM: nvidia_frontend_ioctl: minor 255, module->ioctl failed, error -22
~~~

**Comment by philmmanjaro** [comment] 2015-09-02 21:17
Seems you just installed the kernel driver but not the matching **nvidia-utils**. All packages need to have the same version. Otherwise you create unexpected issues.

**Comment by udeved** [comment] 2015-09-03 07:08
Wrong, the message suggests it, but of course, I installed the utils.

**Comment by philmmanjaro** [comment] 2015-09-04 05:58
Did you yet reboot your machine? also try to call `mkinitcpio -p linux41`

**Comment by philmmanjaro** [comment] 2015-09-04 06:05
I really see no issue here:
```
[phil@manjaro ~]$ dmesg | grep NVIDIA
[   10.708632] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  355.11  Wed Aug 26 16:35:41 PDT 2015
[phil@manjaro ~]$ cat /var/log/Xorg.0.log | grep 355.11
[    23.334] (II) NVIDIA GLX Module  355.11  Wed Aug 26 16:02:11 PDT 2015
[    23.442] (II) NVIDIA dlloader X Driver  355.11  Wed Aug 26 15:38:55 PDT 2015
```

**Comment by udeved** [comment] 2015-09-04 06:05
yes and yes.

Another explanation, perhaps something went wrong with sync.
One can't install the kernel module without specific util-linux version.

**Comment by udeved** [comment] 2015-09-06 15:08
Nope, I have cleaned pacman cache, problem persists.
Even worse, the new kernel doesn't work with 352 modules.
So I have to recompile kernel temporarily with 352 modules.


http://s7.postimg.org/pqqrl70wb/nv_borked.png

**Comment by philmmanjaro** [comment] 2015-09-06 18:29
Which kernel do you referring to? I checked all modules as I'm currently running the **355** drivers on my end. I also updated **340** and **304**. Do they work better on your hardware? On the **346** series there was also another release. The **352** drivers, if you want to keep them, you have to recompile as the kernel-abi changed due **overlayfs** patches. I simply can't support all drivers here. Lets see what the future will bring.

**Comment by udeved** [comment] 2015-09-06 18:33
linux41, I think you bumped the release version yesterday.
I had 352 in cache, but upon boot, nvidia module failed to load with new kernel release version.

I have also had a look at nv release notes, and my card should be supported by new driver still.

I will test later arch kernel with arch nv, as I recompiled kernel41 and 352 an hour ago.

Atm, 355 is a no go for me, but I will also have a test on gentoo perhaps tomorrow.

**Comment by philmmanjaro** [comment] 2015-09-06 18:53
Yep, with [linux41 4.1.6-3](https://github.com/manjaro/packages-core/commit/171890b0d0ab7af9794fc0302e3216ae94994f25) the [ABI](http://kernelnewbies.org/ABI) changed.

**Comment by jetm** [comment] 2015-09-14 15:51
@udeved: I had similar issue with 355.11. I temporally solved installing 340.xx series. My hardware is a Nvidia Quadro K2100M. Check [1] output.

Now, according to Nvidia, my recommended driver is the 352.xx series. The 355.xx series support my hardware as well, but it's a [short-lived version](https://www.nvidia.com/object/unix.html). I  recommend to use long-lived version (352.xx series). Our current problem should a regression in 355.xx series (355.11 latest version). 352.xx series is more stable than 355.xx series.

@philmmanjaro: I think you should consider to restore and keep 352.xx series because is a [long-lived version](https://www.nvidia.com/object/unix.html). You can see long-lived version equivalent to LTS; [further reading](https://www.phoronix.com/scan.php?page=news_item&px=OTkxOA).  
If you need help to keep 352.xx series, I can contribute by maintaining and testing this series in my hardware. I have experience with shell scripting, Arch Linux packing, C/C++ and building Linux kernels. Manjaro is my distribution of choice at work and home.

[1]
According to Nvidia, 352 series is the recommended version for my Nvidia hardware:

$ pyvidia -v
OS: Linux x86_64
Searching for NVIDIA device...
Device Found: NVIDIA Corporation GK106GLM [Quadro K2100M] 
Device ID: 11FC
Required Current Driver Series: 352.xx
Latest Driver Version: 352.41
Download URL: http://us.download.nvidia.com/XFree86/Linux-x86_64/352.41/NVIDIA-Linux-x86_64-352.41.run

**Comment by philmmanjaro** [comment] 2015-09-15 06:02
For me it is no problem to introduce a **nvidia-352xx** package. Let me think about it.

**Comment by udeved** [comment] 2015-09-16 21:20
The issue also occurs on gentoo.
It probably time to file a bug report at nvidia.

**Comment by philmmanjaro** [comment] 2015-09-16 21:23
Seems to be a regression for your hardware then. You can also use the forum [devtalk](https://devtalk.nvidia.com/default/topic/522835/linux/if-you-have-a-problem-please-read-this-first/).

**Comment by philmmanjaro** [comment] 2015-10-05 07:01
It is now a huge topic at [devtalk](https://devtalk.nvidia.com/default/topic/881804/linux/not-alone-vga-dvi-issue-on-355-11-linux-driver-/).

**Comment by philmmanjaro** [comment] 2015-10-20 06:18
Any chance that [358](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20151012/004589.html) fixes this?

**Comment by udeved** [comment] 2015-10-20 07:54
I tried 358 on gentoo already, still borked for my card.

**Comment by philmmanjaro** [comment] 2015-10-20 17:52
Hmm, so this regression is somehow ongoing then ...

**Comment by jetm** [comment] 2015-10-20 17:56
@philmmanjaro Yes, I had same issue with 358xx, no with 352xx.

**Comment by philmmanjaro** [comment] 2015-10-20 17:59
I don't know what Nvidia is doing here. Either fingers crossed it get fixed with the final 358 release or we might downgrade back to the stable 352 which got released two days ago.

**Comment by philmmanjaro** [comment] 2015-10-20 18:57
Did you guys tried **xrandr** yet:
> Comment by th3voic3 (th3voic31) - Sunday, 11 October 2015, 14:16 GMT
> I found a workaround. Using xrandr to set the resolution with the switch "--rate 60" gives me my proper resolution.

**Comment by philmmanjaro** [comment] 2015-10-20 19:03
> Supay 2015-10-08 18:18:57
> The only way I have been able to sort this out is to go into the Nvidia X Server settings GUI utility and in the X Server Display Configuration tab change my selection from my Viewsonic display to "X Screen 0".  That now has me back onto my 1680x1050 with no black bars.

**Comment by udeved** [comment] 2015-10-20 19:07
I haven't fiddled with the borked drivers, no time.
I tired them, and blacklisted them.

**Comment by philmmanjaro** [comment] 2015-10-20 19:31
I really hope **Nvidia** will fix this probably soon ...

**Comment by udeved** [comment] 2015-10-20 19:40
Yeah, but its not really a problem on gentoo, but on manjaro is bit ugly.
Make my kernel experiments more intensive, so I stopped it until fixed.

**Comment by philmmanjaro** [comment] 2015-10-20 19:43
Sure, on my end it works. However I've a lower resolution and a standard 4:3 screen here. That way I never noticed something to be wrong. Since we have other drivers available I see this not so urgent as we have some alternative. However this is one of the few issues we have in a wider range with these drivers ...

**Comment by jetm** [comment] 2015-10-20 19:50
I am still thinking get back the stable 352xx series is the solution here. No only because this issue, also for possible issues might appears later, due to use a **non-stable** Nvidia version.

**Comment by udeved** [comment] 2015-10-20 19:51
I use the 352, but compiled them.
What version started to support egl

**Comment by philmmanjaro** [comment] 2015-10-20 20:04
I had a feeling with this driver. Nvidia changed a lot with this series. Downgrading involves to put an epoch out there. Also by adding a new driver package I've to modify several other packages like **mhwd-db** to notice that new driver, **manjaro-tools** to get info about the driver and optional disable it when not present on live-cd. I know, even the Nvidia page recommends for my hardware to use **352** currently. What I don't understand is, why Nvidia doesn't react, even several people already complained about it. **358** doesn't change it, as it is based-of **355**.

Downgrading back to **1:352.55** is an option to hide this, but not fixing it. We don't even have to start to talk about **Catalyst** drivers and their shape. It is tricky ...

**Comment by udeved** [comment] 2015-10-20 20:09
I do have 352-mhwd-nvidia any arch on disk.

**Comment by philmmanjaro** [comment] 2015-10-20 20:17
Na, we have to create anyway new packages if we go back. However this is more like:

* do we use just long-lived drivers
* do we want another nvidia-352xx we don't know for how long
* or do we have this "broken" driver in our repos until Nvidia fixes it, in example with 358 series

As of now there are several workarounds to temporally fix it. It is more or less how much engine we put into this one. **nvidia** was always the latest driver, regardless if long-lived or not. This is a rare issue, which even I don't have with the current setup.

Driver development seems to be a black box. I even wrote the maintainer an e-mail about his issue right after you reported it.

**Comment by udeved** [comment] 2015-10-20 20:22
In my opinion, we should provide 352.11 if nvidia also recommend it.
I mean, we got a stable branch, they should be in there to satisfy stable.

Perhaps related?
https://forum.manjaro.org/index.php?topic=27624.msg231594;topicseen#msg231594
I'm gonna ask what gpu drivers.

**Comment by philmmanjaro** [comment] 2015-10-20 20:23
Current driver of this branch is **352.55**.

**Comment by philmmanjaro** [comment] 2015-10-20 20:39
Quick google search what I found so far:

* [FS#46544 - [nvidia] 355.11 has problem with connections over VGA or DVI ](https://bugs.archlinux.org/task/46544)
* [Not alone : VGA/DVI issue on 355.11 linux driver ](https://devtalk.nvidia.com/default/topic/881804/not-alone-vga-dvi-issue-on-355-11-linux-driver-/)
* [Strange behaviour with 2 screens and linux & nvidia update](https://bbs.archlinux.org/viewtopic.php?id=203035)
* [Is it worth it upgrading from nvidia-340 to nvidia-355?](https://www.reddit.com/r/linux_gaming/comments/3o8w1t/is_it_worth_it_upgrading_from_nvidia340_to/)

As Ubuntu 15.10 already ships with a broken **Catalyst** and now with a broken **Nvidia** this will be fun after all. I still believe those companies will act fast ...

**Comment by philmmanjaro** [comment] 2015-10-23 07:48
> Aaron Plattner just requests more feedback:
> I'm sorry, I forgot to ask for a verbose log with mode validation information. You can get that by either starting X from the console with "startx -- -logverbose 6" or by running "sudo nvidia-xconfig --mode-debug" and then restarting the X server. 

Seems Nvidia now wants to fix this issue ...

**Comment by philmmanjaro** [comment] 2015-10-31 09:55
I decided now to downgrade to **352.55** since no proper fix is in sight:
https://github.com/manjaro/packages-extra/commit/4995e5adc5c7a9bc004903fc7b74eb95c039bebb
https://github.com/manjaro/packages-multilib/commit/fee4cbf8fa99f24e9ec0a4f91b498af27f8ddfe5

**Comment by jetm** [comment] 2015-10-31 13:13
:+1:

**Comment by oberon2007** [comment] 2015-10-31 14:27
But is there a dependency problem now? https://forum.manjaro.org/index.php?topic=27843.msg233932#msg233932

**Comment by ringo32** [comment] 2015-10-31 14:42
probably he need to downgrade his nvidia-utils ?

**Comment by jonathonf** [comment] 2015-10-31 16:15
Just to say I have had no issues with Nvidia drivers at all (MSI GT-70).

Three things here:

1. 358.09 is a beta driver release so shouldn't make it to the stable repos.
2. adding an epoch to the packages is going to make maintenance more faff in future. If you're deprecating 358.09 you should probably just remove the package - if it's only in unstable it won't affect general users. However,
3. if 352.55 is an LTS release this should have its own package. Then anyone with issues can use that version instead without imposing on people who don't have issues.

**Comment by philmmanjaro** [comment] 2015-10-31 17:18
The issues are fixed and **epoch** no problem. I simply forgot about it. With **355.xx** and higher we have more issues than with the current recommended **352.xx** series. Creating another nvidia package makes no sense for me. However the latest **352.55** included new card support and fixes. We will see when Nvidia stabilize their higher drivers.

@jonathonf: sure, I've neither issues with the newer drivers, but I saw lot of issues posted over at devtalk.nvidia.com.

**Comment by philmmanjaro** [comment] 2015-11-17 23:56
Quick question. Does the short lived driver **358.13** fixes the screen issue for you? How ever you have to create your own packages out of source to try it. @udeved: did you test this already on **Gentoo**?

**Comment by udeved** [comment] 2015-11-18 10:31
Nope, haven't tested yet, tbh, I hate to play with gpu drivers, I usually take gentoo stable driver, and just wait until they mark next one stable.
I can have a test perhaps tonight if its in portage tree.

**Comment by philmmanjaro** [comment] 2015-11-20 19:50
As soon as I've some feedback to **358.13** I'll update the PKGBUILDs ...

**Comment by jetm** [comment] 2015-11-20 20:28
@philmmanjaro: There is a [new 352.xx stable release (352.33)](https://www.nvidia.com/Download/driverResults.aspx/95159/en-us). Looking in the release notes: 
* Fixed a regression that prevented DPMS from working correctly on some DisplayPort displays.

It appears this fix solve my issue with DisplayPort display.
 
Do you have a plan to update the PKGBUILDS for that version as well?

Thanks.

**Comment by philmmanjaro** [comment] 2015-11-20 20:31
@jetm: I plan to update them by tomorrow. As of now it is to late and I'm also not in the mood to do packages right now ...

**Comment by jetm** [comment] 2015-11-23 21:05
@philmmanjaro: I tested the new stable nvidia release: 352.63. It fixed my issue with DisplayPort display.

Regards.

**Comment by philmmanjaro** [comment] 2015-11-23 22:03
@jetm: thx for the feedback.

**Closed** 2016-02-09 22:23 UTC
