### ISSUE TITLE
[xf86-video-intel] "swallowing" xcursor and dropbox-icon

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-extra#51] opened 2016-02-17 19:40 UTC
https://forum.manjaro.org/index.php?topic=31095.msg256959#msg256959
https://forum.manjaro.org/index.php?topic=31084.msg256648#msg256648
https://github.com/manjaro/packages-community/commit/21f0e3cde707919dea566247d7843d9607b6535e#commitcomment-16108690

**Comment by philmmanjaro** [comment] 2016-02-17 19:49
Please summarize these and involve [Chris Wilson](mailto:chris@chris-wilson.co.uk) from Intel.

**Comment by philmmanjaro** [comment] 2016-02-17 22:07
Tell me if **xf86-video-intel 1:2.99.917+550+g636b529-1** helps ...

**Comment by oberon2007** [comment] 2016-02-17 22:09
We'll have to ask on the forum. I cannot reproduce the issue here ... ;)

**Comment by oberon2007** [comment] 2016-02-17 22:09
Oh, @kirek maybe?

**Comment by oberon2007** [comment] 2016-02-18 11:46
There is another report on the forum now that kernel 4.5 seems to solve the issue in that particular case (don't know, yet if 4.4 might be sufficient already). Don't know which thread that was ... ;) I will find it again later and post the link... Ok, I'll write to Chris Wilson.

**Comment by oberon2007** [comment] 2016-02-18 12:52
So the issue seems to have been introduced with 550. And @philmmanjaro , 552 didn't seem to help in this case at least: https://forum.manjaro.org/index.php?topic=20673.msg257123#msg257123

**Comment by oberon2007** [comment] 2016-02-18 14:30
Here's some detailed information from optics in the forum:
```
Driver: xf86-video-intel-1:2.99.917+552+ge41040f-0.1
kernel: 4.5rc3-1-MANJARO
kernel: 4.4.1-2-MANJARO
- mouse pointer is showing

Driver: xf86-video-intel-1:2.99.917+552+ge41040f-0.1
kernel: 4.3.5-1-MANJARO
kernel: 4.2.8.4-1-MANJARO
kernel: 4.1.17-1-MANJARO
- mouse pointer not showing

Driver: xf86-video-intel-1:2.99.917+550+g636b529-0.1
kernel: 4.5rc3-1-MANJARO
- mouse pointer is showing

Driver: xf86-video-intel-1:2.99.917+550+g636b529-0.1
kernel: 4.2.8.4-1-MANJARO
kernel: 4.1.17-1-MANJARO
- mouse pointer not showing
```

**Comment by philmmanjaro** [comment] 2016-02-18 18:10
Chris just pushed another fix. I'll update the driver once more. Hopefully it is solved by now. Otherwise we have to see what the issue is and give him some details.

**Comment by philmmanjaro** [comment] 2016-02-18 20:09
Check if **xf86-video-intel 1:2.99.917+556+g0532031-0.1** fixes it.

**Comment by Kirek** [comment] 2016-04-09 15:53
dropbox icon issues was a dropbox problem, fixed with https://github.com/manjaro/packages-community/commit/6fcff61eddfa38ec73cf640550d10653ab01bb6d
Is xcursor still a problem? Can this be closed?

**Closed** 2016-04-11 22:01 UTC
